# Generated by Django 5.2.3 on 2025-06-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frtuna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinations',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
